{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-conn
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  url: {{ .Values.secrets.rabbitmq.url | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: order-database
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  url: {{ .Values.secrets.postgres.url | b64enc }}
{{- end }}
