apiVersion: v2
name: velure-datastores
description: Unified Helm chart for Velure datastores (MongoDB, Redis, RabbitMQ)
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: mongodb
    version: 14.12.1
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled

  - name: redis
    version: 18.19.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: rabbitmq
    version: 13.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
