apiVersion: v2
name: velure-datastores
description: Unified Helm chart for Velure datastores (MongoDB, Redis, RabbitMQ)
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: mongodb
    version: 18.1.10
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled

  - name: redis
    version: 24.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: rabbitmq
    version: 16.0.14
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
