apiVersion: apps/v1
kind: Deployment
metadata:
  name: velure-auth
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: velure-auth
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: velure-auth
  template:
    metadata:
      labels:
        app: velure-auth
    spec:
      securityContext:
        fsGroup: 65532
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: AUTH_SERVICE_APP_PORT
              value: "{{ .Values.service.port }}"
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: velure-auth-postgres
                  key: url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: velure-auth-jwt
                  key: secret
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: velure-auth-jwt
                  key: expiresIn
            - name: JWT_REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: velure-auth-jwt
                  key: refreshSecret
            - name: JWT_REFRESH_TOKEN_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: velure-auth-jwt
                  key: refreshExpiresIn
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: velure-auth-session
                  key: secret
            - name: SESSION_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: velure-auth-session
                  key: expiresIn
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            readOnlyRootFilesystem: true
