apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "velure-auth.fullname" . }}-deny-all
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "velure-auth.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "velure-auth.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
