apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "velure-auth.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "velure-auth.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "velure-auth.selectorLabels" . | nindent 6 }}
