apiVersion: v1
kind: Secret
metadata:
  name: velure-auth-postgres
  labels:
    {{- include "velure-auth-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.secrets.postgres.url | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: velure-auth-jwt
  labels:
    {{- include "velure-auth-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.secrets.jwt.secret | quote }}
  expiresIn: {{ .Values.secrets.jwt.expiresIn | quote }}
  refreshSecret: {{ .Values.secrets.jwt.refreshSecret | quote }}
  refreshExpiresIn: {{ .Values.secrets.jwt.refreshExpiresIn | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: velure-auth-session
  labels:
    {{- include "velure-auth-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.secrets.session.secret | quote }}
  expiresIn: {{ .Values.secrets.session.expiresIn | quote }}
