apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: velure-publish-order
  namespace: default
  labels:
    app: velure-publish-order
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: velure-publish-order
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - order
