apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ADMIN_RABBITMQ_USER: {{ .Values.secrets.adminUser | b64enc }}
  ADMIN_RABBITMQ_PASSWORD: {{ .Values.secrets.adminPassword | b64enc }}
  PUBLISHER_RABBITMQ_USER: {{ .Values.secrets.publisherUser | b64enc }}
  PUBLISHER_RABBITMQ_PASSWORD: {{ .Values.secrets.publisherPassword | b64enc }}
  PROCESS_RABBITMQ_USER: {{ .Values.secrets.processUser | b64enc }}
  PROCESS_RABBITMQ_PASSWORD: {{ .Values.secrets.processPassword | b64enc }}
